stages:
  - build

cargo build & run & test:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose
    - cd counter_example
    - cargo run
    - cd ..
    - cd desktop_benchmark
    - cargo run
    - cd ..
    - cd desktop_persist
    - ./run_checked_output_timeout.sh 5s
    - cd ..
    - cd desktop_playground
    - cargo run
    - cd ..


