stages:
  - build

cargo build & run & test:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo test --features enable_general_metadata_runtime_persist --verbose
    - cd counter_example
    - cargo run
    - cd ..
    - cd desktop_benchmark
    - cargo run
    - cd ..
    - cd desktop_playground
    - cargo run
    - cd ..

