stages:
  - build

cargo build & run & test:
  stage: build
  image: rust:1.75.0
  script:
    - rustup toolchain install $(cat rust-toolchain)
    - cargo build --verbose
    - cargo test --verbose
    - cd counter_example
    - cargo run
    - cd ..
    - cd desktop_benchmark
    - cargo run
    - cd ..
    - cd desktop_playground
    - cargo run
    - cd ..

