[package]
name = "vnv_heap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.21", features = [ "max_level_trace", "release_max_level_warn" ] }
linked_list_allocator = { version = "0.10.5", optional = true, features = [] }
buddy_system_allocator = { version = "0.9.1", optional = true, features = [] }
linkme = { version = "0.3.25", optional = true }

[features]
default = ["linked_list_allocator", "buddy_allocator"]
linked_list_allocator = ["dep:linked_list_allocator"]
buddy_allocator = ["dep:buddy_system_allocator"]
test = ["dep:linkme"]

[dev-dependencies]
linkme = "0.3.25"
